name: deploy

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/arm, linux/amd64, linux/arm64/v8]
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: theorangeone
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build containers
        uses: docker/build-push-action@v2
        with:
          platforms: ${{ matrix.platform }}
          push: true
          tags: theorangeone/docker-cgit:latest
